from __future__ import annotations

import argparse
import sys
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROMPT = ROOT / "prompts" / "analyze-standby-issue.md"


def read_optional(path: Path | None, title: str) -> str:
    if path is None:
        return f"## {title}\n\n未提供。\n"
    if not path.exists():
        raise SystemExit(f"Input file not found: {path}")
    return f"## {title}\n\n来源：{path.as_posix()}\n\n{path.read_text(encoding='utf-8')}\n"


def build_context(
    issue: str,
    platform: str,
    scenario: str,
    current: str,
    log_extract: Path | None,
    rag_result: Path | None,
    prompt_template: Path,
) -> str:
    if not prompt_template.exists():
        raise SystemExit(f"Prompt template not found: {prompt_template}")

    prompt = prompt_template.read_text(encoding="utf-8")
    metadata = dedent(
        f"""
        # Claude Code 待机功耗分析上下文

        ## 问题描述

        {issue}

        ## 基本信息

        | 字段 | 内容 |
        |---|---|
        | 平台/版本 | {platform or '未提供'} |
        | 测试场景 | {scenario or '未提供'} |
        | 电流数据 | {current or '未提供'} |
        """
    ).strip()

    sections = [
        metadata,
        read_optional(log_extract, "日志辅助分析结果").rstrip(),
        read_optional(rag_result, "RAG 检索结果").rstrip(),
        "## 分析要求\n\n请基于以上问题、日志证据和 RAG 知识，输出标准待机功耗问题分析报告。不要编造未提供的数据；缺失信息请放到“需要补充的信息”。",
        "## 使用的报告模板\n\n" + prompt.rstrip(),
    ]
    return "\n\n".join(sections).rstrip() + "\n"


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="Build Claude Code analysis context from issue, log evidence, and RAG result.")
    parser.add_argument("--issue", required=True, help="Issue description.")
    parser.add_argument("--platform", default="", help="Platform, software version, or hardware version.")
    parser.add_argument("--scenario", default="", help="Test scenario.")
    parser.add_argument("--current", default="", help="Expected/measured current data.")
    parser.add_argument("--log-extract", type=Path, help="Markdown file generated by scripts/analyze_log.py.")
    parser.add_argument("--rag-result", type=Path, help="Markdown file generated by rag/query.py.")
    parser.add_argument("--prompt-template", type=Path, default=DEFAULT_PROMPT, help="Analysis prompt template path.")
    parser.add_argument("--output", type=Path, required=True, help="Output Markdown context path.")
    args = parser.parse_args()

    context = build_context(
        issue=args.issue,
        platform=args.platform,
        scenario=args.scenario,
        current=args.current,
        log_extract=args.log_extract,
        rag_result=args.rag_result,
        prompt_template=args.prompt_template,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(context, encoding="utf-8")
    print(f"Wrote analysis context to {args.output}")


if __name__ == "__main__":
    main()
